[package]
name = "hello-tokio"
version = "0.0.0"
edition.workspace = true

[dependencies]
areq-tokio = { workspace = true, features = ["http1", "tls"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }

[lints]
workspace = true
