[package]
name = "hello-smol"
version = "0.0.0"
edition.workspace = true

[dependencies]
areq-smol = { workspace = true, features = ["http1", "rtn"] }
async-executor.workspace = true
futures-lite.workspace = true

[lints]
workspace = true
