[workspace]
resolver = "2"
members = [
    "areq",
    "areq-body",
    "areq-h1",
    "examples/fetch",
    "examples/h1-fetch",
]

[workspace.dependencies]
areq = { version = "=0.1.0", path = "areq" }
areq-body = { version = "=0.1.0", path = "areq-body" }
areq-h1 = { version = "=0.1.0", path = "areq-h1" }
async-executor = "1.13"
async-io = "2.3"
async-net = "2.0"
bytes = "1.8"
futures-lite = "2.4"
http = "1.1"
pin-project-lite = "0.2"
url = "2.5"

[workspace.lints.clippy]
manual-assert = "deny"
match-wildcard-for-single-variants = "deny"
missing-assert-message = "deny"
semicolon-if-nothing-returned = "deny"
trivially-copy-pass-by-ref = "deny"
use-self = "deny"
unwrap-used = "deny"
