[package]
name = "areq"
description = "Async runtime independent HTTP requests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
areq-body.workspace = true
areq-h1.workspace = true
async-io.workspace = true
bytes.workspace = true
futures-lite.workspace = true
h2 = "0.4"
http.workspace = true
pin-project-lite.workspace = true
tokio = "1.41"
url.workspace = true

[lints]
workspace = true
