[package]
name = "areq-h1"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
bytes.workspace = true
futures-core.workspace = true
futures-io.workspace = true
http.workspace = true
httparse = "1.9.4"

[dev-dependencies]
async-executor.workspace = true
async-io.workspace = true
async-net.workspace = true
futures-lite.workspace = true
hyper = { version = "1", features = ["http1", "server"] }
http-body-util = "0.1"
serde_json = "1.0"
smol-hyper = "0.1.1"
