[package]
name = "serve"
version = "0.0.0"
edition.workspace = true

[dependencies]
areq.workspace = true
async-channel.workspace = true
async-executor.workspace = true
async-io.workspace = true
async-net.workspace = true
hyper = { version = "1.5.0", features = ["http1", "server"] }
smol-hyper = { version = "0.1.1" }
tower = { version = "0.5.1", features = ["util"] }

[dependencies.axum]
version = "0.7"
default-features = false
features = ["http1"]

[lints]
workspace = true
