[package]
name = "fetch"
version = "0.0.0"
edition.workspace = true

[dependencies]
areq = { workspace = true, features = ["http1", "http2", "tls"] }
async-net.workspace = true
futures-lite.workspace = true

[lints]
workspace = true
