[package]
name = "h1-fetch"
version = "0.0.0"
edition.workspace = true

[dependencies]
areq-h1.workspace = true
async-net.workspace = true
futures-lite.workspace = true
http.workspace = true

[lints]
workspace = true
