[package]
name = "areq-body"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
futures-lite.workspace = true

[dev-dependencies]
async-io.workspace = true

[lints]
workspace = true
